apiVersion: v1
kind: Service
metadata:
  name: hospital
  namespace: hospital
  labels:
    app: hospital
spec:
  selector:
    app: hospital
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
