---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: hospital
spec:
  encryptedData:
    mysql-database: AgBCLN+w8dK1zeXpeOjE7w3tZ6AdG5OxP40huC7wBzSX/S8m/BdhSVNmyjSQJ7JSLTbCaV1ERr4oLe1g8ujNA+dEkZqol3XrbNigg8ZQ2O0/MgZgfMwHsIb7kMd43jfSVlmwJ9va7v/yynaF9H0SpbIKfYA9V6ykePyYaqlAB/Crd6nDqlJ3WNcWI+4/he1i6yGUsSGAK8wEJ7DGn4wxmSQk1oEKOtDzlmKjU5R7ZWqsX9hkP7s1uW26z83QOxOW7SxU7eX/vbnmeGWtRxsjCwb51Mo8cuq+aG+XW3l3KP239nidsV+n0KW9RslWxud58CiE1Wb0F+C2Ba6jBrLf1td/9pAWKl9sOvkxtrBFYXOfGUN/eSURc5n/fQN0D0Iu3qN2TIF7KVeFiJsEqPj8Wm4EIHpEpBw2ZLqxzmttZ6eanxBHSq8qrD/pQPhZpjO3NQgC824SS1ZKbz1eGUzKmhBjvcdswy1f1nsy6qrcWY1hMwTr15Hy5DbOvogZxTROKilna0RWybXSEpdAomCbCBEPvr1gxhieqr66srHKdrMVsyD/BGs9XHxJfQIVexMRkkVVG5q/mmTDk9hs+mVq1nCrJBoSolewgGkzhY40rvyxYxvRP+1Zxws98nPxvEqK2E7tDPV93rzY/8GdOPjbIJnTZPYOTtJrsSGRmHsanpJluQwCKn5rcGsEWsFt9tn2Vu4mOgfiaEiD0g==
    mysql-root-password: AgANQODBIDihQKZnoDwfezeyQFxELzguCkaZVBZiFQpjpvNaaNZXFSWvSequwUZVVwDpoTYnsHPh7Rzw0AKv1VlnV1AkZxFBHRTZtyCxOCo5tSLMNwnvMDyhumRWlYwjEXEkevUavr1KksMDcq38Ydu8nYSbmobupsFXh3ir3Gfsn5MxktsF3cjKSFUu+d0lP6TcNqK/HCAcBrFyObEC1ACt7O4cH/er+qaUQ/V+P2tetd/MSo0Ub1RM6akAOt56fR2M96/7B+eetmEw9dm62RJdFo1pmhHO5P33u9gi5CsGv8G6bcxX7n+KsVGRgJhlUwkJxRA818QQUc5rgiTWB9yFIEjRGNvFWH98LXk6tv4IjeUVYX0UrSLE9JcxJ9Cxi1gBJhja0UiB8yyhXZ7JxyX1+11GeeIg1e7boUKSO4cyIu4raau17EAADE5kXgXByFVfUQiBv4FghIqyY4g6KJz42kSOtOkqTDwp4H8hxr/mKBqWJK5+LowWLqxVNaZLp61W30HkJkFAkAA8SGBfGtwTV3U1onvZoF+L+evwJcaDswurhtupDuQy++RC9V8b1ZoWZE7E+WIEkyUWeAlCmoVBU7p2B06aWwUqYuwfAF9+w8W2ywZVILBMoDiaKQhUPWFcDhCNQzzVaVIHhKd9JVrgZb/uvje/zlPHZnW01UI53aTeq2513scQskxNxZzUwXhFA9AA
  template:
    metadata:
      name: mysql-secret
      namespace: hospital
